# This file was automatically generated. Any edit will be lost.

TEMPLATE = app
QT += testlib
# XXX TODO: Qt += widgets? should this be manually specified? Added by default?

# XXX Everything below should be  autogenerated and included as:
# include($$OUT_PWD/.config.pri)

INCLUDEPATH += $$PWD/../../../testsuite/
unix: QMAKE_CXXFLAGS += $$QMAKE_CFLAGS_ISYSTEM $$PWD/../../../testsuite/

INCLUDEPATH += $$PWD/../../../../src/libs/
unix: QMAKE_CXXFLAGS += $$QMAKE_CFLAGS_ISYSTEM $$PWD/../../../../src/libs/

INCLUDEPATH += $$PWD/../../../../src/third/
unix: QMAKE_CXXFLAGS += $$QMAKE_CFLAGS_ISYSTEM $$PWD/../../../../src/third/

HEADERS = Test_Core_Foo.h
SOURCES = Test_Core_Foo.cpp

# That prl stuff really seems broken.
# The prl file is created, and it include the
# correct info, but the link_prl ignores it completely.
CONFIG += create_prl link_prl

unix:  LIBS += -L../../../../src/libs/Core/ -lCore
win32: LIBS += -L../../../../src/libs/Core/$$RELEASE_OR_DEBUG/ -lCore

unix:  LIBS += -L../../../../src/third/Geometry/ -lGeometry
win32: LIBS += -L../../../../src/third/Geometry/$$RELEASE_OR_DEBUG/ -lGeometry

#unix:       PRE_TARGETDEPS += /home/boris/Documents/build-QtProjectTemplate-Desktop_Qt_5_5_1_GCC_64bit-Release/src/third/Geometry/libGeometry.a
#win32-g++:  PRE_TARGETDEPS += /home/boris/Documents/build-QtProjectTemplate-Desktop_Qt_5_5_1_GCC_64bit-Release/src/third/Geometry/$$RELEASE_OR_DEBUG/libGeometry.a
#else:win32: PRE_TARGETDEPS += /home/boris/Documents/build-QtProjectTemplate-Desktop_Qt_5_5_1_GCC_64bit-Release/src/third/Geometry/$$RELEASE_OR_DEBUG/Geometry.lib
